version: '2'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: "always"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
  viz:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9090:8080
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
          - MYSQL_DATABASE=openmrs
          - MYSQL_ROOT_PASSWORD=debezium
          - MYSQL_USER=mysqluser
          - MYSQL_PASSWORD=mysqlpw
          - MYSQL_ROOT_HOST=172.%    # Allow docker contatiners to connect to mysql
    volumes:
        - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
        - ./dbdump:/docker-entrypoint-initdb.d

  openmrs:
    restart: "always"
    image: openmrs/openmrs-reference-application-distro:latest
    container_name: openmrs
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - "8080:8080"
    environment:
      DB_DATABASE: 'openmrs'
      DB_HOST: mysql
      DB_USERNAME: 'mysqluser'
      DB_PASSWORD: 'mysqlpw'
      #DB_CREATE_TABLES: 'true'
      #DB_AUTO_UPDATE: 'true'
      #MODULE_WEB_ADMIN: 'true'
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    container_name: zookeeper
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - CREATE_TOPICS= "input:1:3,output:1:3"
    container_name: kafka
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
    container_name: mysql-connect

# other important containers - uncomment to install
  kafka-schema-registry:
    container_name: kafka-schema-registry
    image: confluentinc/cp-schema-registry:4.0.0
    hostname: kafka-schema-registry
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeper:2181
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - zookeeper
      - kafka

  schema-registry-ui:
    container_name: schema-registry-ui
    image: landoop/schema-registry-ui:0.9.3
    hostname: kafka-schema-registry-ui
    ports:
      - "8001:8000"
    environment:
      SCHEMAREGISTRY_URL: http://kafka-schema-registry:8081/
      PROXY: "true"
    depends_on:
      - kafka-schema-registry

  kafka-rest-proxy:
    container_name: kafka-rest-proxy
    image: confluentinc/cp-kafka-rest:4.0.0
    hostname: kafka-rest-proxy
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - zookeeper
      - kafka
      - kafka-schema-registry

  kafka-topics-ui:
    container_name: kafka-topics-ui
    image: landoop/kafka-topics-ui:0.9.3
    hostname: kafka-topics-ui
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    depends_on:
      - zookeeper
      - kafka
      - kafka-schema-registry
      - kafka-rest-proxy

## Not really important
#  kafka-connect-ui:
#    container_name: kafka-connect-ui
#    image: landoop/kafka-connect-ui:0.9.3
#    hostname: kafka-connect-ui
#    ports:
#      - "8003:8000"
#    environment:
#      CONNECT_URL: "http://kafka-connect:8083/"
#      PROXY: "true"
#    depends_on:
#      - connect
#
#  zoonavigator-api:
#    container_name: zoonavigator-api
#    image: elkozmon/zoonavigator-api:0.2.3
#    environment:
#      SERVER_HTTP_PORT: 9000
#    restart: unless-stopped
#    depends_on:
#      - zookeeper
#
#  zoonavigator-web:
#    container_name: zoonavigator-web
#    image: elkozmon/zoonavigator-web:0.2.3
#    ports:
#      - "8004:8000"
#    environment:
#       API_HOST: "zoonavigator-api"
#       API_PORT: 9000
#    links:
#      - zoonavigator-api
#    depends_on:
#      - zoonavigator-api
#    restart: unless-stopped